# Generated by Django 4.2.7 on 2023-11-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_hint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hint", name="hint1", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="hint", name="hint2", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="hint", name="hint3", field=models.TextField(null=True),
        ),
    ]
